version: 2
updates:
  # Check npm dependencies daily
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'eimi-codes'
    assignees:
      - 'eimi-codes'
    commit-message:
      prefix: 'chore(deps):'
      prefix-development: 'chore(dev-deps):'
      include: 'scope'
    allow:
      - dependency-type: 'all'
    pull-request-branch-name:
      separator: '/'

  # Check GitHub Actions monthly
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'eimi-codes'
    assignees:
      - 'eimi-codes'
    commit-message:
      prefix: 'ci(actions):'
      include: 'scope'
